# Generated by Django 4.0.6 on 2022-07-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('constitution', models.IntegerField(default=0)),
                ('vigor', models.IntegerField(default=0)),
                ('strengh', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('char_class', models.ManyToManyField(related_name='charclass', to='rpg.charclass')),
                ('inventory', models.ManyToManyField(related_name='items', to='rpg.item')),
                ('left_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftweapon', to='rpg.weapon')),
                ('right_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rightweapon', to='rpg.weapon')),
            ],
        ),
    ]
