# Generated by Django 4.0.6 on 2022-07-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_remove_character_char_class_character_char_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='remain_points',
            field=models.IntegerField(default=0),
        ),
    ]
