# Generated by Django 4.0.6 on 2022-08-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_attributes_remove_character_charisma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='attributes',
        ),
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='strengh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='vigor',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
    ]
