# Generated by Django 4.0.6 on 2022-09-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0009_item_generic_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
